export const CONTENT_MSG_TYPE = 'content_msg_type'
export const MSG_ID_SEED = new Date().getTime()
export const CONTENT_MSG_BIZ_GET_CONFIG = 'CONTENT_MSG_BIZ_GET_CONFIG'
export const CONTENT_MSG_BIZ_SAVE_CONFIG = 'CONTENT_MSG_BIZ_SAVE_CONFIG'
export const CONTENT_MSG_BIZ_NEW_DATA_DETECTED = 'CONTENT_MSG_BIZ_NEW_DATA_DETECTED'
